version: 0.1

phases:
  build:
    commands:
      - apt-get install git
      - apt-get install unzip
      - git init
      - git clone https://github.com/ShivaniAgrawal049/TerraformResource.git
      - wget https://releases.hashicorp.com/terraform/0.13.2/terraform_0.13.2_linux_amd64.zip
      - unzip terraform_0.13.2_linux_amd64.zip
      - ./terraform init
      - ./terraform plan

  post_build:
    commands:
      - ./terraform apply
