version: 0.1

phases:
  build:
    commands:
      - docker-compose build

  post_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 887733174116.dkr.ecr.ap-south-1.amazonaws.com
      - docker tag flaskapp_flaskapp:latest 887733174116.dkr.ecr.ap-south-1.amazonaws.com/application:latest
      - docker push 887733174116.dkr.ecr.ap-south-1.amazonaws.com/application:latest
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 887733174116.dkr.ecr.ap-south-1.amazonaws.com
      - docker tag flaskapp_nginx:latest 887733174116.dkr.ecr.ap-south-1.amazonaws.com/webserver:latest
      - docker push 887733174116.dkr.ecr.ap-south-1.amazonaws.com/webserver:latest
