version: 0.1

phases:
  build:
    commands:
      - apt-get install unzip
      - wget https://releases.hashicorp.com/terraform/0.13.2/terraform_0.13.2_linux_amd64.zip
      - unzip terraform_0.13.2_linux_amd64.zip
      - echo $"export PATH=\$PATH:$(pwd)" >> ~/.bash_profile
      - source ~/.bash_profile
      - terraform init
      - terraform apply

  post_build:
    commands:
      - terraform apply
