---
- hosts: localhost
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: installed
  - name: Install mod_wsgi-python27.x86_64
    yum:
      name: mod_wsgi-python27.x86_64
      state: installed
  - name: Install git
    yum:
      name: git
      state: installed
